services:

  redis:
    image: "redis:alpine"
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: unless-stopped

  postgres_db:
    image: postgres:13 
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: neuro_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped

  api:
    build:
      context: ./app
      target: api
    container_name: fastapi_app
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres_db
      - worker
    environment:
      - DEVELOPMENT=${DEVELOPMENT}
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
      - CONNECTION_STRING_POSTGRES=${CONNECTION_STRING_POSTGRES}
      - DEBUG=${DEBUG}  
      - DEBUG_WORKER=${DEBUG_WORKER}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}  
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - BASE_URL=${BASE_URL}
      - REDIS_STRING=${REDIS_STRING}
      - LOG_LEVEL=${LOG_LEVEL}
      - TMP_DIR=${TMP_DIR}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - AD_AI_URL=${AD_AI_URL}
    networks:
      - backend
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  worker:
    build:
      context: ./app
      target: worker
    container_name: celery_worker
    depends_on:
      - redis
      - postgres_db
    environment:
      - DEVELOPMENT=${DEVELOPMENT}
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
      - CONNECTION_STRING_POSTGRES=${CONNECTION_STRING_POSTGRES}
      - DEBUG=${DEBUG}  
      - DEBUG_WORKER=${DEBUG_WORKER}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}  
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - BASE_URL=${BASE_URL}
      - REDIS_STRING=${REDIS_STRING}
      - LOG_LEVEL=${LOG_LEVEL}
      - TMP_DIR=${TMP_DIR}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - AD_AI_URL=${AD_AI_URL}
    networks:
      - backend
    mem_limit: 4g
    mem_reservation: 2g
    cpus: 2.0
    restart: unless-stopped
    command: ["celery", "-A", "celery_app.config:celery_app", "worker", "--beat", "--loglevel=info"]

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
    enable_ipv6: true
